[project]
name = "parallax-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "tqdm>=4.65.0",
    "sentence-transformers>=2.2.2",
    "chromadb>=0.5.4,<0.6",
]
